"""Added Route Tables

Revision ID: f8dc6503b7b0
Revises: d42343752ab0
Create Date: 2025-10-29 18:15:17.231226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dc6503b7b0'
down_revision = 'd42343752ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('total_distance_meters', sa.Integer(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('encoded_polyline', sa.Text(), nullable=True),
    sa.Column('waypoints_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('google_route_id', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=True),
    sa.Column('shared_with_route_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_departure_time', sa.DateTime(), nullable=True),
    sa.Column('scheduled_return_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['google_route_id'], ['google_routes.id'], ),
    sa.ForeignKeyConstraint(['shared_with_route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.String(length=20), nullable=True),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=False),
    sa.Column('estimated_departure_time', sa.DateTime(), nullable=False),
    sa.Column('distance_from_previous_meters', sa.Integer(), nullable=True),
    sa.Column('duration_from_previous_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_meetings')
    op.drop_table('routes')
    op.drop_table('google_routes')
    # ### end Alembic commands ###
